Feature/cleanup
LUSHDigital/microservice-core-golang pull request #5
Opened 2017-10-04 15:41 UTC by LadyDascalie

This provides a bunch of improvements to how the documentation displays in GoDoc (and gets rid of redundant information)

This also renames `formatters.go` and `routes.go` to names matching their actual package name

2017-10-04 17:07 UTC, danmrichards requested changes

2017-10-04 17:07 UTC, danmrichards commented on format/format.go
> +// Pckage format defines any necessary custom formatters for the responses
Typo (Pckage -> Package)

2017-10-04 17:07 UTC, danmrichards commented on pagination/paginator.go
> +// Package pagnination defines a paginator able to return formatted responses
Typo (pagnination -> pagination)

2017-10-04 17:07 UTC, danmrichards commented
Just a couple typos @LadyDascalie then LGTM

2017-10-04 19:22 UTC, LadyDascalie commented
typos fixed

2017-10-05 08:36 UTC, danmrichards approved these changes

2017-10-05 08:36 UTC, merged